server:
  port: 3379

spring:
  application:
    name: spring-sleuth-haystack
  sleuth:
    enabled: true
    haystack:
      enabled: true
      idformat: string
      client:
        grpc:
          host: localhost
          port: 34000
    sampler:
      probability: 1.0



logging.level.org.springframework.web: info